# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main", "workflow-branch" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3 
      with:   
        auto-update-conda: true
        activate-environment: myenv 
        environment-file: environment.yml
        auto-activate-base: false
    - name: Activate conda
      shell: bash -el {0}
      run: conda info
    - name: List conda
      shell: bash -el {0}
      run: conda list
    - name: Compile program
      shell: bash -el {0}
      run: sh compile.sh
    - name: Run test
      shell: bash -el {0}
      run: ./simple_tests



